### ISSUE TITLE
另存为功能

### ISSUE THREAD

**Issue by zchrissirhcz** [ffiirree/Capturer#21]
Hi, thank you for sharing this repo.

截图后的编辑功能（写字、马赛克、橡皮擦），用起来都挺好；
想问下是否会支持 “另存为“ 功能 ？ 目前的 Ctrl + S 会存储在默认路径， 不能每次另行指定存储路径，如果可以支持，就更加好用了。

**Comment by ffiirree** [comment]
可以的，有空后会尽快实现
