### ISSUE TITLE
ffmpeg添加到了环境变量，但是还是编译失败

### ISSUE THREAD

**Issue by wy-luke** [ffiirree/Capturer#22]
在命令行输入ffmpeg可以得到输出

但是使用VS2022编译的时候，还是报错，ffmpeg not found....

我下载了 ffmpeg win full ，也装了 ffmpeg-tools 还是不行，或者说是要别的？

求助😭

**Comment by ffiirree** [comment]
你要下载动态库的版本，shared那个，解压后bin有libavformat.dll的那个版本，然后把根目录和bin目录放到环境产量中

**Comment by wy-luke** [comment]
编译成功了，但是我运行项目报错了

![error](https://user-images.githubusercontent.com/25719685/168283769-a9f898f5-c7db-416e-95e9-3342ca909b03.png)

**Comment by ffiirree** [comment]
这个是用cmake管理的工程，现在vs也支持cmake工程了，cmake工程跨平台比较好啊。

错误你把报错的文件和行号发出来

**Comment by ffiirree** [comment]
你用vs的话，就别用那些编译命令了，直接在里编译运行

**Comment by wy-luke** [comment]
![Snipaste_2022-05-13_20-45-25](https://user-images.githubusercontent.com/25719685/168285834-adf99f37-7984-4b2f-ae4b-45eb4aaadb63.png)

这是行号

运行的时候是选这个吗？

![截图_20220513204451](https://user-images.githubusercontent.com/25719685/168285896-ef54dc5f-0e37-44f7-9dc3-08ad5ba8b4a5.png)

**Comment by ffiirree** [comment]
Current document那里，下拉选capturer.exe

**Comment by wy-luke** [comment]
OK，选了capturer.exe，还有一个后面带了一个括号(install)，不是那个吧

选了后，运行还是报错。

（谢谢大佬！！！）

**Comment by ffiirree** [comment]
不带install的，错误过会儿我看看，水平有限(◞‸◟ )

**Comment by wy-luke** [comment]
我换成4可以了，但是又显示，找不到 Qt5Widgetsd.dll等等那些文件，我看了一下在cmakelist里面的路径是没问题的呀

**Comment by wy-luke** [comment]
可以了，我把那些dll都放到exe的目录里面了，感谢！！！！
