### ISSUE TITLE
无法cmake

### ISSUE THREAD

**Issue by Toin1779712664** [ffiirree/Capturer#28]
你好，我在github上clone该代码库，并按照相应的操作进行cmake但是它提示我：
CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find FFmpeg (missing: avdevice) (found version "56.31.100")
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindFFmpeg.cmake:168 (find_package_handle_standard_args)
  CMakeLists.txt:31 (find_package)
相应的系统版本是（Ubuntu 20.4）且安装最新版的ffmpeg

**Comment by ffiirree** [comment]
> Could NOT find FFmpeg (missing: avdevice) (found version "56.31.100")
检查一下安装FFmpeg过程中缺失了avdevice库，终端随便一个ffmpeg，看前面的打印信息中各个组件的版本，例如：
````
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100   # 是否缺失
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
````
缺失则安装：
```sh
sudo apt install libavdevice-dev
```
