### ISSUE TITLE
[Preview] Support Video / GIF

### ISSUE THREAD

**Issue by ffiirree** [ffiirree/Capturer#48]

**Comment by thc10** [comment]
你好，我想请问一下，视频播放的功能是正在优化吗？我测试了一下使用现在的VideoPlayer去播放视频，会遇到跳转不准、多次跳转导致卡死以及关闭播放窗口时整个窗口无响应的问题。
不知道上述问题是不是我的用法不对导致的，我测试VideoPlayer的方法是在menu里面加了一个Aciton，然后调用了VideoPlayer的Open函数去打开了一个指定的文件，在这个播放的过程中有什么需要注意的事项吗？

**Comment by ffiirree** [comment]
对的，现在视频播放还在开发，不怎么稳定，我打算花一段时间重写一下这部分，有些乱。

打开视频后，再用菜单打开文件，需要把各种资源和变量都重置好。你现在出现问题是用 **复制文件，F3贴出预览视频** 的时候出现的吗

**Comment by thc10** [comment]
我在工具栏里面没有找到视频播放器的入口，只看到了截屏/录制/相机/设置这几个功能选项，不知道是不是已经有在工具里面接入这个播放器？
我现在是在menu里面加了一个同级于 截图/录制/设置的按钮，然后在Capture中创建了一个VideoPlayer的对象。点击menu中的播放的时候，调用了VideoPlayer的Open函数去打开一个mp4文件直接开始播放的~

不知道是否方便加一下联系方式？这是我的QQ : 738433477
