### ISSUE TITLE
二次改变截取区域大小的时候 Magnifier 中显示的颜色是截图边框的颜色

### ISSUE THREAD

**Issue by cs2130** [ffiirree/Capturer#58]
QPixmap Magnifier::grab() const
{
    const auto rect = grabRect();
    if (desktop_.isNull()) {
        return QGuiApplication::primaryScreen()->grabWindow(
            probe::graphics::virtual_screen().handle, rect.x(), rect.y(), rect.width(), rect.height());
    }

    return desktop_.copy(rect);
}

**Comment by ffiirree** [comment]
是个bug，谢谢

**Comment by cs2130** [comment]
简单修复了一下, 自己先用着, 
`
void Selector::mousePressEvent(QMouseEvent *event)
{
    auto pos = event->globalPos();
    if (event->button() == Qt::LeftButton && status_ != SelectorStatus::LOCKED) {
        cursor_pos_ = box_.absolutePos(pos);
        switch (status_) {
        case SelectorStatus::PREY_SELECTING:
#ifdef _WIN32
            if (scope_ == scope_t::display) {
                auto display = probe::graphics::display_contains(pos);
                if (display.has_value()) {
                    box_.range(display.value().geometry);
                }
            }
#endif 
            sbegin_ = pos;
            status(SelectorStatus::PREY_SELECTING | SelectorStatus::FREE_SELECTING);
            break;

        case SelectorStatus::CAPTURED:
            if (cursor_pos_ == ResizerLocation::EMPTY_INSIDE) {
                move_spos_ = move_epos_ = pos;
                status(SelectorStatus::MOVING);
            }
            else if (!!(cursor_pos_ & ResizerLocation::ADJUST_AREA)) {
                emit resizeFresh(); //-- 窗口大小变化,进行刷新
                status(SelectorStatus::RESIZING);
            }
            break;

        default: loge("error status"); break;
        }
    }
}`

`   
connect(selector_, &Selector::resizeFresh, this, [this]() {
           const auto menuv = menu_->isVisible();
           if (menuv) { menu_->hide(); }
           auto pixmap = QPixmap::fromImage(backgroundBrush().textureImage());
           QPainter painter(&pixmap);
           scene()->render(&painter, pixmap.rect());
           magnifier_->setGrabPixmap(pixmap);
       });
`

**Comment by cs2130** [comment]
简单修复了一下,自己先用着, 感谢开源了这么好的截图软件!

```
void Selector::mousePressEvent(QMouseEvent *event)
{
    auto pos = event->globalPos();
    if (event->button() == Qt::LeftButton && status_ != SelectorStatus::LOCKED) {
        cursor_pos_ = box_.absolutePos(pos);
        switch (status_) {
        case SelectorStatus::PREY_SELECTING:
#ifdef _WIN32
            if (scope_ == scope_t::display) {
                auto display = probe::graphics::display_contains(pos);
                if (display.has_value()) {
                    box_.range(display.value().geometry);
                }
            }
#endif 
            sbegin_ = pos;
            status(SelectorStatus::PREY_SELECTING | SelectorStatus::FREE_SELECTING);
            break;

        case SelectorStatus::CAPTURED:
            if (cursor_pos_ == ResizerLocation::EMPTY_INSIDE) {
                move_spos_ = move_epos_ = pos;
                status(SelectorStatus::MOVING);
            }
            else if (!!(cursor_pos_ & ResizerLocation::ADJUST_AREA)) {
                emit resizeFresh(); //-- 改变窗口大小,刷新
                status(SelectorStatus::RESIZING);
            }
            break;

        default: loge("error status"); break;
        }
    }
}
```

```
connect(selector_, &Selector::resizeFresh, this, [this]() {
        const auto menuv = menu_->isVisible();
        if (menuv) { menu_->hide(); }
        auto pixmap = QPixmap::fromImage(backgroundBrush().textureImage());
        QPainter painter(&pixmap);
        scene()->render(&painter, pixmap.rect());
        magnifier_->setGrabPixmap(pixmap);
    });
```

**Comment by ffiirree** [comment]
👍
