### ISSUE TITLE
Recovering a screen recording video file after a crash

### ISSUE THREAD

**Issue by Lehnemann** [ffiirree/Capturer#62]
Hi, and thanks again for your reply...

Please, I was recording my computer's screen when I was stroke by a black-out. The video file appears like this in the video recording folder.

![image](https://github.com/user-attachments/assets/b915684f-aba0-4896-bc73-c0a88a1985e4)

Is there a way to recover what was left from the video's file? 🙂

Thanks again...

**Comment by ffiirree** [comment]
I have no idea, it's maybe very hard to decode the broken file
