### ISSUE TITLE
Compilation Failure: libcap\CMakeLists.txt:9: error: Can not find the suitable version.

### ISSUE THREAD

**Issue by XMuli** [ffiirree/Capturer#63]
Hello, found this to be great project, thanks for your efforts!
Two questions:
- Can I receive your IM(QQ or Other) account via e-mail? Discuss the contribution of participation in the screenshot (I have sent a general description by e-mail, and would like to discuss in detail)
- How to compile it successfully? The details are as follows:

I'm not very familiar with FFmpeg, so I downloaded two versions to try:

https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-full-shared.7z and https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-n7.1-latest-win64-gpl-shared-7.1.zip. 

I tried placing their **bin** folders in the system path one after the other, and then attempted to compile. However, I encountered the following error:

```bash
->[ENV]
Windows 10  22H2
Qt 6.8.0 + 5.15.2

->[Build Errror Output]
D:\projects\Capturer\libcap\CMakeLists.txt:9: error: Can not find the suitable version.

Call stack:
  D:/projects/Capturer/libcap/CMakeLists.txt:9 (find_package)
  D:/projects/Capturer/3rdparty/cmake-modules/FindFFmpeg.cmake:147 (message)

--> code error: find_package(FFmpeg 7.0 REQUIRED)
```

SYSTEM PATH: 
- `D:\projects\third\libass_0.17.3_msvc17\bin\x64` 
- `D:\projects\third\ffmpeg-7.1-full_build-shared\bin`

![image](https://github.com/user-attachments/assets/fbfdae66-30f5-46b3-bac2-7e5bfb4a6060)

Thanks
I look forward to hearing from you.

**Comment by ffiirree** [comment]
我收到你的邮件了，但是我最近没有精力继续开发。
