### ISSUE TITLE
视频录制时保存问题

### ISSUE THREAD

**Issue by duoduoaixiaogai** [ffiirree/Capturer#9]
视频录制后保存到了什么地方。找不到。

**Comment by duoduoaixiaogai** [comment]
你的这个录制视频的支持声音吗，还有代码 编译不过去 qxtglobalshortcut.h 没有这个文件 我只在3rdparty目录中找到了这个目录 但是没有找到这个头文件。

**Comment by duoduoaixiaogai** [comment]
你的这个录制视频的支持声音吗，还有代码编译不过去qxtglobalshortcut.h没有这个文件我只在第三方目录中找到了这个目录但是没有找到这个头文件。

**Comment by ffiirree** [comment]
还不支持声音。
这个头文件包含在一个子库里，参考README看看能不能解决你的问题。
